In [79]:
# load package
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity

### 用切有次數的 keywords 來做 (會重複keywords)

In [80]:
# read article 
df_all = pd.read_csv('../../input/stage1.csv', header = 0, names=["id", "article", "words"])
# df_all = pd.read_csv('../../input/stage2.csv', header = 0, names=["id", "article", "words"])
# df_all = df_all[0:5]
df_all

id  \
1     梅雨季來臨，文旦黑點病易發生，請注意病徵，以及早加強防治措施。 5月已進入梅雨季節，近日連續...   
10    天氣多變溫差大，近山區及偏施氮肥田區稻熱病發病較為嚴重，籲請農友注意防治。花蓮區農改場、防檢...   
1000  新聞稿-稻熱病進入好發季節，防檢局籲請農友加強防範 行政院農業委員會動植物防疫檢疫局（以下簡...   
1005  稻熱病進入好發季節，防檢局籲請農友加強防治 農委會防檢局表示，自3月起全國各地水稻生長陸續進...   
1007  乍暖還寒，防檢局籲請農友加強防治稻熱病 農委會防檢局表示，全國各地水稻生長陸續進入分蘗期，因...   
...                                                 ...   
986   苗栗區農業改良場發佈水稻白葉枯病警報 糧食作物病蟲害發生警報中華民國90年9月21日發佈第3...   
988   雨後適合稻熱病發生，請持續進行監測並指導農民防治 依據氣象預報，今年自五月中旬起，臺灣地區即...   
992   新入侵果實蠅緊急撲滅模擬演習  新聞稿 新入侵植物害蟲緊急撲滅演習產官學總動員嚴防外來疫病蟲...   
997   梨木蝨危害，請農友注意防範 梨木蝨危害，請農友注意防範行政院農業委員會動植物防疫檢疫局(以下...   
998   防範梨木蝨危害，請農友配合實施共同防治 行政院農業委員會動植物防疫檢疫局表示，為有效控制中部...   

                       article  \
1     ['chem', 'crop', 'pest']   
10    ['chem', 'crop', 'pest']   
1000          ['crop', 'pest']   
1005          ['crop', 'pest']   
1007          ['crop', 'pest']   
...                        ...   
986   ['chem', 'crop', 'pest']   
988           ['crop', 'pest']   
992           ['crop', 'pest']   
997   ['chem', 'crop', 'pest']   
998   ['chem', 'crop', 'pest']   

                                                  words  
1     ['鋅錳乃浦', '鋅錳乃浦', '鋅錳乃浦水懸劑', '鋅錳乃浦可濕性粉劑', '錳乃浦'...  
10    ['亞磷酸', '微生物製劑', '三賽唑', '三賽唑', '三賽唑可濕性粉劑', '三賽...  
1000  ['水稻', '水稻', '水稻', '水稻', '水稻', '水稻', '稻熱病', '稻...  
1005  ['水稻', '水稻', '水稻', '水稻', '水稻', '水稻', '稻熱病', '稻...  
1007  ['水稻', '水稻', '水稻', '水稻', '稻熱病', '稻熱病', '稻熱病', ...  
...                                                 ...  
986   ['三賽唑', '三賽唑可濕性粉劑', '三賽唑可濕性粉', '賽唑可濕性粉劑', '撲殺熱...  
988   ['水稻', '水稻', '水稻', '梅', '稻熱病', '稻熱病', '稻熱病', '...  
992   ['梨', '果樹', '桃', '柑桔', '柑桔', '疫病', '疫病', '疫病',...  
997   ['益達胺', '益達胺溶液', '亞滅培', '亞滅培可溶性粉劑', '梨', '梨', ...  
998   ['益達胺', '益達胺溶液', '亞滅培', '亞滅培可溶性粉劑', '梨', '梨', ...  

[560 rows x 3 columns]

In [81]:
# # read result file
# result_all_df = pd.read_csv('../../output/results_similarity_jac_stage1.csv', header = 0)
# result_all_df

In [82]:
# compute tf
vectorizer = CountVectorizer() 
text_count_vector = vectorizer.fit_transform(df_all.words)
tf_vector = text_count_vector.toarray()
tf_vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [83]:
# compute tf-idf
tfidf_transfomer = TfidfTransformer()
docs_tfidf = tfidf_transfomer.fit_transform(text_count_vector)
tfidf_vector = docs_tfidf.toarray()
tfidf_vector

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [84]:
tf_similarity = cosine_similarity(tf_vector, tf_vector)

# 删除對角線元素(自己對自己)
tf_similarity = tf_similarity[~np.eye(tf_similarity.shape[0],dtype=bool)].reshape(tf_similarity.shape[0],-1)
tf_similarity.flatten()

array([0.        , 0.        , 0.        , ..., 0.        , 0.04965363,
       0.97997035])

In [85]:
tfidf_similarity = cosine_similarity(tfidf_vector, tfidf_vector)

# 删除對角線元素(自己對自己)
tfidf_similarity = tfidf_similarity[~np.eye(tfidf_similarity.shape[0],dtype=bool)].reshape(tfidf_similarity.shape[0],-1)
tfidf_similarity.flatten()

array([0.        , 0.        , 0.        , ..., 0.        , 0.02493781,
       0.98369463])

In [86]:
result_df_multi = pd.DataFrame({"tf_cosine_multi_keyword":tf_similarity.flatten(),
                                "tfidf_cosine_multi_keyword":tfidf_similarity.flatten()})
result_df_multi

tf_cosine_multi_keyword  tfidf_cosine_multi_keyword
0                      0.000000                    0.000000
1                      0.000000                    0.000000
2                      0.000000                    0.000000
3                      0.000000                    0.000000
4                      0.000000                    0.000000
...                         ...                         ...
313035                 0.000000                    0.000000
313036                 0.000000                    0.000000
313037                 0.000000                    0.000000
313038                 0.049654                    0.024938
313039                 0.979970                    0.983695

[313040 rows x 2 columns]

### 用切有出現的 keywords 來做 (不重複、無計數)

In [87]:
# read article 
df_all = pd.read_csv('../../input/test3.csv', header = 0, names=["id", "article", "words"])
# df_all = pd.read_csv('../../input/stage2.csv', header = 0, names=["id", "article", "words"])
# df_all = df_all[0:5]
df_all

id  \
1     梅雨季來臨，文旦黑點病易發生，請注意病徵，以及早加強防治措施。 5月已進入梅雨季節，近日連續...   
10    天氣多變溫差大，近山區及偏施氮肥田區稻熱病發病較為嚴重，籲請農友注意防治。花蓮區農改場、防檢...   
1000  新聞稿-稻熱病進入好發季節，防檢局籲請農友加強防範 行政院農業委員會動植物防疫檢疫局（以下簡...   
1005  稻熱病進入好發季節，防檢局籲請農友加強防治 農委會防檢局表示，自3月起全國各地水稻生長陸續進...   
1007  乍暖還寒，防檢局籲請農友加強防治稻熱病 農委會防檢局表示，全國各地水稻生長陸續進入分蘗期，因...   
...                                                 ...   
986   苗栗區農業改良場發佈水稻白葉枯病警報 糧食作物病蟲害發生警報中華民國90年9月21日發佈第3...   
988   雨後適合稻熱病發生，請持續進行監測並指導農民防治 依據氣象預報，今年自五月中旬起，臺灣地區即...   
992   新入侵果實蠅緊急撲滅模擬演習  新聞稿 新入侵植物害蟲緊急撲滅演習產官學總動員嚴防外來疫病蟲...   
997   梨木蝨危害，請農友注意防範 梨木蝨危害，請農友注意防範行政院農業委員會動植物防疫檢疫局(以下...   
998   防範梨木蝨危害，請農友配合實施共同防治 行政院農業委員會動植物防疫檢疫局表示，為有效控制中部...   

                       article  \
1     ['chem', 'crop', 'pest']   
10    ['chem', 'crop', 'pest']   
1000          ['crop', 'pest']   
1005          ['crop', 'pest']   
1007          ['crop', 'pest']   
...                        ...   
986   ['chem', 'crop', 'pest']   
988           ['crop', 'pest']   
992           ['crop', 'pest']   
997   ['chem', 'crop', 'pest']   
998   ['chem', 'crop', 'pest']   

                                                  words  
1     ['貝芬硫可濕性粉劑', '硫水懸劑', '硫可濕性粉劑', '鋅錳乃浦', '鋅錳乃浦水懸...  
10    ['亞磷酸', '微生物製劑', '三賽唑', '三賽唑可濕性粉劑', '三賽唑水懸劑', ...  
1000                      ['水稻', '稻熱病', '穗稻熱病', '葉稻熱病']  
1005                      ['水稻', '稻熱病', '穗稻熱病', '葉稻熱病']  
1007                              ['水稻', '稻熱病', '葉稻熱病']  
...                                                 ...  
986   ['三賽唑', '三賽唑可濕性粉劑', '三賽唑可濕性粉', '賽唑可濕性粉劑', '撲殺熱...  
988                                  ['水稻', '梅', '稻熱病']  
992       ['梨', '果樹', '桃', '柑桔', '疫病', '果實蠅', '地中海果實蠅']  
997   ['益達胺', '益達胺溶液', '亞滅培', '亞滅培可溶性粉劑', '梨', '梨木蝨'...  
998   ['益達胺', '益達胺溶液', '亞滅培', '亞滅培可溶性粉劑', '梨', '高接梨'...  

[560 rows x 3 columns]

In [88]:
# compute tf
vectorizer = CountVectorizer() 
text_count_vector = vectorizer.fit_transform(df_all.words)
tf_vector = text_count_vector.toarray()
tf_vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [89]:
# compute tf-idf
tfidf_transfomer = TfidfTransformer()
docs_tfidf = tfidf_transfomer.fit_transform(text_count_vector)
tfidf_vector = docs_tfidf.toarray()
tfidf_vector

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [90]:
tf_similarity = cosine_similarity(tf_vector, tf_vector)

# 删除對角線元素(自己對自己)
tf_similarity = tf_similarity[~np.eye(tf_similarity.shape[0],dtype=bool)].reshape(tf_similarity.shape[0],-1)
tf_similarity.flatten()

array([0.        , 0.        , 0.        , ..., 0.        , 0.15811388,
       0.80178373])

In [91]:
tfidf_similarity = cosine_similarity(tfidf_vector, tfidf_vector)

# 删除對角線元素(自己對自己)
tfidf_similarity = tfidf_similarity[~np.eye(tfidf_similarity.shape[0],dtype=bool)].reshape(tfidf_similarity.shape[0],-1)
tfidf_similarity.flatten()

array([0.        , 0.        , 0.        , ..., 0.        , 0.09612135,
       0.79013767])

In [92]:
result_df_once = pd.DataFrame({"tf_cosine_once_keyword":tf_similarity.flatten(),
                               "tfidf_cosine_once_keyword":tfidf_similarity.flatten()})
result_df_once

tf_cosine_once_keyword  tfidf_cosine_once_keyword
0                     0.000000                   0.000000
1                     0.000000                   0.000000
2                     0.000000                   0.000000
3                     0.000000                   0.000000
4                     0.000000                   0.000000
...                        ...                        ...
313035                0.000000                   0.000000
313036                0.000000                   0.000000
313037                0.000000                   0.000000
313038                0.158114                   0.096121
313039                0.801784                   0.790138

[313040 rows x 2 columns]

### 輸出合併結果

In [93]:
# combine_result = pd.concat([result_all_df,result_df], axis=1)
# combine_result

In [97]:
result_df = pd.concat([result_df_once, result_df_multi],axis=1)
result_df

tf_cosine_once_keyword  tfidf_cosine_once_keyword  \
0                     0.000000                   0.000000   
1                     0.000000                   0.000000   
2                     0.000000                   0.000000   
3                     0.000000                   0.000000   
4                     0.000000                   0.000000   
...                        ...                        ...   
313035                0.000000                   0.000000   
313036                0.000000                   0.000000   
313037                0.000000                   0.000000   
313038                0.158114                   0.096121   
313039                0.801784                   0.790138   

        tf_cosine_multi_keyword  tfidf_cosine_multi_keyword  
0                      0.000000                    0.000000  
1                      0.000000                    0.000000  
2                      0.000000                    0.000000  
3                      0.000000                    0.000000  
4                      0.000000                    0.000000  
...                         ...                         ...  
313035                 0.000000                    0.000000  
313036                 0.000000                    0.000000  
313037                 0.000000                    0.000000  
313038                 0.049654                    0.024938  
313039                 0.979970                    0.983695  

[313040 rows x 4 columns]

In [95]:
# combine_result.to_csv("../../output/results_similarity_jac_cos_stage1.csv", index= False)
result_df.to_csv("../../output/results_cos_keywords_stage1.csv", index= False)
# combine_result.to_csv("../../output/results_simi_cosSimi_stage2.csv", index= False)

In [96]:
# End of file