In [2]:
# load package
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity

### 用切有次數的 keywords 來做 (會重複keywords)

In [3]:
# read article 
# df_all = pd.read_csv('../../input/stage1.csv', header = 0, names=["id", "article", "words"])
df_all = pd.read_csv('../../input/stage2_keyword.csv', header = 0, names=["id", "article", "words"])
# df_all = df_all[0:5]
df_all

id  \
1001  稻熱病進入好發季節，防檢局籲請農友加強防範 九十三年四月二十一日動植物防疫檢疫局發布之新聞稿...   
1004  全民一起來監測紅火蟻 農委會防檢局表示，自3月份起氣溫逐漸回暖，正是紅火蟻開始活躍的季節，也...   
1006  系統測試公告 有關96年1月29日發布之"蔥、蒜紫斑病及薊馬危害日益嚴重，台南農改場籲請農民...   
1008  二期作水稻生育初期，請注意縱捲葉蟲之防治 縱捲葉蟲原本在水稻第一、二期作之孕穗期至齊穗期為害...   
1009  請農友加強水稻瘤野螟及白葉枯病防治 農委會防檢局表示，全國各地二期水稻生長陸續進入孕穗期，依...   
...                                                 ...   
991   儘速耕除綠肥作物，慎防斜紋夜蛾密度上升 一、依據新聞報導，在新竹、雲林及嘉義等地區因休耕農田...   
993   請農民在「全國滅鼠週」全力配合田間滅鼠工作 請農民在「全國滅鼠週」全力配合田間滅鼠工作行政院...   
994   培育健康秧苗，預防水稻徒長病及立枯病發生 培育健康秧苗，預防水稻徒長病及立枯病發生行政院農業...   
996   水稻進入分蘗盛期請農友加強防範水稻稻熱病 行政院農業委員會動植物防疫檢疫局表示，自本（九十二...   
999   預防梨木蝨危害，請農友及早實施共同防治 九十三年一月二十八日預防梨木蝨危害，請農友及早實施共...   

                       article  \
1001          ['crop', 'pest']   
1004          ['crop', 'pest']   
1006          ['crop', 'pest']   
1008  ['chem', 'crop', 'pest']   
1009          ['crop', 'pest']   
...                        ...   
991           ['crop', 'pest']   
993                         []   
994   ['chem', 'crop', 'pest']   
996   ['chem', 'crop', 'pest']   
999   ['chem', 'crop', 'pest']   

                                                  words  
1001  ['水稻', '水稻', '水稻', '水稻', '水稻', '水稻', '稻熱病', '稻...  
1004  ['桃', '紅火蟻', '紅火蟻', '紅火蟻', '紅火蟻', '紅火蟻', '紅火蟻'...  
1006                                 ['蔥', '紫斑病', '薊馬']  
1008  ['陶斯松', '陶斯松乳劑', '歐殺松', '歐殺松可溶性粉劑', '水稻', '水稻'...  
1009  ['水稻', '水稻', '水稻', '水稻', '水稻', '水稻', '水稻', '瘤野...  
...                                                 ...  
991   ['田菁', '綠肥作物', '綠肥作物', '綠肥作物', '斜紋夜蛾', '斜紋夜蛾',...  
993                                                  []  
994   ['三賽唑', '撲殺熱', '芬普尼', '撲克拉', '披扶座', '依得利', '免賴...  
996   ['三賽唑', '三賽唑', '亞賜圃', '嘉賜三賽唑', '撲殺熱', '富米熱斯', ...  
999   ['益達胺', '益達胺溶液', '亞滅培', '亞滅培可溶性粉劑', '梨', '梨', ...  

[421 rows x 3 columns]

In [4]:
# # read result file
# result_all_df = pd.read_csv('../../output/results_similarity_jac_stage1.csv', header = 0)
# result_all_df

In [5]:
# compute tf
vectorizer = CountVectorizer() 
text_count_vector = vectorizer.fit_transform(df_all.words)
tf_vector = text_count_vector.toarray()
tf_vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [6]:
# compute tf-idf
tfidf_transfomer = TfidfTransformer()
docs_tfidf = tfidf_transfomer.fit_transform(text_count_vector)
tfidf_vector = docs_tfidf.toarray()
tfidf_vector

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
tf_similarity = cosine_similarity(tf_vector, tf_vector)

# 删除對角線元素(自己對自己)
tf_similarity = tf_similarity[~np.eye(tf_similarity.shape[0],dtype=bool)].reshape(tf_similarity.shape[0],-1)
tf_similarity.flatten()

array([0.        , 0.        , 0.24110086, ..., 0.        , 0.        ,
       0.        ])

In [8]:
tfidf_similarity = cosine_similarity(tfidf_vector, tfidf_vector)

# 删除對角線元素(自己對自己)
tfidf_similarity = tfidf_similarity[~np.eye(tfidf_similarity.shape[0],dtype=bool)].reshape(tfidf_similarity.shape[0],-1)
tfidf_similarity.flatten()

array([0.        , 0.        , 0.10848065, ..., 0.        , 0.        ,
       0.        ])

In [9]:
result_df_multi = pd.DataFrame({"tf_cosine_multi_keyword":tf_similarity.flatten(),
                                "tfidf_cosine_multi_keyword":tfidf_similarity.flatten()})
result_df_multi

tf_cosine_multi_keyword  tfidf_cosine_multi_keyword
0                      0.000000                    0.000000
1                      0.000000                    0.000000
2                      0.241101                    0.108481
3                      0.231800                    0.106533
4                      0.000000                    0.000000
...                         ...                         ...
176815                 0.000000                    0.000000
176816                 0.000000                    0.000000
176817                 0.000000                    0.000000
176818                 0.000000                    0.000000
176819                 0.000000                    0.000000

[176820 rows x 2 columns]

### 用切有出現的 keywords 來做 (不重複、無計數)

In [10]:
# read article 
# df_all = pd.read_csv('../../input/test3.csv', header = 0, names=["id", "article", "words"])
df_all = pd.read_csv('../../input/stage2_only_keyword.csv', header = 0, names=["id", "article", "words"])
# df_all = df_all[0:5]
df_all

id                                            article  \
0    1001  稻熱病進入好發季節，防檢局籲請農友加強防範 九十三年四月二十一日動植物防疫檢疫局發布之新聞稿...   
1    1004  全民一起來監測紅火蟻 農委會防檢局表示，自3月份起氣溫逐漸回暖，正是紅火蟻開始活躍的季節，也...   
2    1006  系統測試公告 有關96年1月29日發布之"蔥、蒜紫斑病及薊馬危害日益嚴重，台南農改場籲請農民...   
3    1008  二期作水稻生育初期，請注意縱捲葉蟲之防治 縱捲葉蟲原本在水稻第一、二期作之孕穗期至齊穗期為害...   
4    1009  請農友加強水稻瘤野螟及白葉枯病防治 農委會防檢局表示，全國各地二期水稻生長陸續進入孕穗期，依...   
..    ...                                                ...   
416   991  儘速耕除綠肥作物，慎防斜紋夜蛾密度上升 一、依據新聞報導，在新竹、雲林及嘉義等地區因休耕農田...   
417   993  請農民在「全國滅鼠週」全力配合田間滅鼠工作 請農民在「全國滅鼠週」全力配合田間滅鼠工作行政院...   
418   994  培育健康秧苗，預防水稻徒長病及立枯病發生 培育健康秧苗，預防水稻徒長病及立枯病發生行政院農業...   
419   996  水稻進入分蘗盛期請農友加強防範水稻稻熱病 行政院農業委員會動植物防疫檢疫局表示，自本（九十二...   
420   999  預防梨木蝨危害，請農友及早實施共同防治 九十三年一月二十八日預防梨木蝨危害，請農友及早實施共...   

                                                 words  
0                        ['水稻', '稻熱病', '穗稻熱病', '葉稻熱病']  
1                                         ['桃', '紅火蟻']  
2                                   ['蔥', '紫斑病', '薊馬']  
3    ['陶斯松', '陶斯松乳劑', '歐殺松', '歐殺松可溶性粉劑', '水稻', '瘤野螟...  
4                                ['水稻', '瘤野螟', '白葉枯病']  
..                                                 ...  
416                             ['田菁', '綠肥作物', '斜紋夜蛾']  
417                                                 []  
418  ['三賽唑', '撲殺熱', '芬普尼', '撲克拉', '披扶座', '依得利', '免賴...  
419  ['三賽唑', '亞賜圃', '嘉賜三賽唑', '撲殺熱', '富米熱斯', '加普', '...  
420  ['益達胺', '益達胺溶液', '亞滅培', '亞滅培可溶性粉劑', '梨', '疫病',...  

[421 rows x 3 columns]

In [11]:
# compute tf
vectorizer = CountVectorizer() 
text_count_vector = vectorizer.fit_transform(df_all.words)
tf_vector = text_count_vector.toarray()
tf_vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
# compute tf-idf
tfidf_transfomer = TfidfTransformer()
docs_tfidf = tfidf_transfomer.fit_transform(text_count_vector)
tfidf_vector = docs_tfidf.toarray()
tfidf_vector

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
tf_similarity = cosine_similarity(tf_vector, tf_vector)

# 删除對角線元素(自己對自己)
tf_similarity = tf_similarity[~np.eye(tf_similarity.shape[0],dtype=bool)].reshape(tf_similarity.shape[0],-1)
tf_similarity.flatten()

array([0.       , 0.       , 0.1767767, ..., 0.       , 0.       ,
       0.       ])

In [14]:
tfidf_similarity = cosine_similarity(tfidf_vector, tfidf_vector)

# 删除對角線元素(自己對自己)
tfidf_similarity = tfidf_similarity[~np.eye(tfidf_similarity.shape[0],dtype=bool)].reshape(tfidf_similarity.shape[0],-1)
tfidf_similarity.flatten()

array([0.        , 0.        , 0.06120031, ..., 0.        , 0.        ,
       0.        ])

In [15]:
result_df_once = pd.DataFrame({"tf_cosine_once_keyword":tf_similarity.flatten(),
                               "tfidf_cosine_once_keyword":tfidf_similarity.flatten()})
result_df_once

tf_cosine_once_keyword  tfidf_cosine_once_keyword
0                     0.000000                   0.000000
1                     0.000000                   0.000000
2                     0.176777                   0.061200
3                     0.288675                   0.119242
4                     0.000000                   0.000000
...                        ...                        ...
176815                0.000000                   0.000000
176816                0.000000                   0.000000
176817                0.000000                   0.000000
176818                0.000000                   0.000000
176819                0.000000                   0.000000

[176820 rows x 2 columns]

### 輸出合併結果

In [16]:
# combine_result = pd.concat([result_all_df,result_df], axis=1)
# combine_result

In [17]:
result_df = pd.concat([result_df_once, result_df_multi],axis=1)
result_df

tf_cosine_once_keyword  tfidf_cosine_once_keyword  \
0                     0.000000                   0.000000   
1                     0.000000                   0.000000   
2                     0.176777                   0.061200   
3                     0.288675                   0.119242   
4                     0.000000                   0.000000   
...                        ...                        ...   
176815                0.000000                   0.000000   
176816                0.000000                   0.000000   
176817                0.000000                   0.000000   
176818                0.000000                   0.000000   
176819                0.000000                   0.000000   

        tf_cosine_multi_keyword  tfidf_cosine_multi_keyword  
0                      0.000000                    0.000000  
1                      0.000000                    0.000000  
2                      0.241101                    0.108481  
3                      0.231800                    0.106533  
4                      0.000000                    0.000000  
...                         ...                         ...  
176815                 0.000000                    0.000000  
176816                 0.000000                    0.000000  
176817                 0.000000                    0.000000  
176818                 0.000000                    0.000000  
176819                 0.000000                    0.000000  

[176820 rows x 4 columns]

In [18]:
# combine_result.to_csv("../../output/results_similarity_jac_cos_stage1.csv", index= False)
result_df.to_csv("../../output/results_cos_keywords_stage2.csv", index= False)
# combine_result.to_csv("../../output/results_simi_cosSimi_stage2.csv", index= False)

In [96]:
# End of file