In [9]:
# load package
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
# read data unigram
df_unigram = pd.read_csv('../../input/stage1_unigram.csv', header = 0, names=["id", "article", "words"])
df_unigram = df_unigram[0:5]
df_unigram

id                                            article  \
0     1  梅雨季來臨，文旦黑點病易發生，請注意病徵，以及早加強防治措施。 5月已進入梅雨季節，近日連續...   
1    10  天氣多變溫差大，近山區及偏施氮肥田區稻熱病發病較為嚴重，籲請農友注意防治。花蓮區農改場、防檢...   
2  1000  新聞稿-稻熱病進入好發季節，防檢局籲請農友加強防範 行政院農業委員會動植物防疫檢疫局（以下簡...   
3  1005  稻熱病進入好發季節，防檢局籲請農友加強防治 農委會防檢局表示，自3月起全國各地水稻生長陸續進...   
4  1007  乍暖還寒，防檢局籲請農友加強防治稻熱病 農委會防檢局表示，全國各地水稻生長陸續進入分蘗期，因...   

                                               words  
0  ['梅雨季', '來臨', '文旦', '黑點病', '易_發生', '請', '注意', ...  
1  ['天氣', '多變', '溫差', '山區', '偏施_氮肥', '田區', '稻熱病',...  
2  ['新聞稿', '稻熱病', '進入', '好發_季節', '防檢局', '籲請_農友', ...  
3  ['稻熱病', '進入', '好發_季節', '防檢局', '籲請_農友_加強', '防治'...  
4  ['乍暖還寒', '防檢局', '籲請_農友_加強', '防治', '稻熱病', '農委會'...

In [11]:
# read data once_keyword
df_once_keyword = pd.read_csv('../../input/stage1_only_keyword.csv', header = 0, names=["id", "article", "words"])
df_once_keyword = df_once_keyword[0:5]
df_once_keyword

id                                            article  \
0     1  梅雨季來臨，文旦黑點病易發生，請注意病徵，以及早加強防治措施。 5月已進入梅雨季節，近日連續...   
1    10  天氣多變溫差大，近山區及偏施氮肥田區稻熱病發病較為嚴重，籲請農友注意防治。花蓮區農改場、防檢...   
2  1000  新聞稿-稻熱病進入好發季節，防檢局籲請農友加強防範 行政院農業委員會動植物防疫檢疫局（以下簡...   
3  1005  稻熱病進入好發季節，防檢局籲請農友加強防治 農委會防檢局表示，自3月起全國各地水稻生長陸續進...   
4  1007  乍暖還寒，防檢局籲請農友加強防治稻熱病 農委會防檢局表示，全國各地水稻生長陸續進入分蘗期，因...   

                                               words  
0  ['鋅錳乃浦', '鋅錳乃浦水懸劑', '鋅錳乃浦可濕性粉劑', '錳乃浦', '錳乃浦可濕...  
1  ['亞磷酸', '微生物製劑', '三賽唑', '三賽唑可濕性粉劑', '三賽唑水懸劑', ...  
2                      ['水稻', '稻熱病', '穗稻熱病', '葉稻熱病']  
3                      ['水稻', '稻熱病', '穗稻熱病', '葉稻熱病']  
4                              ['水稻', '稻熱病', '葉稻熱病']

In [12]:
#  read data multi_keyword
df_multi_keyword = pd.read_csv('../../input/stage1_keyword.csv', header = 0, names=["id", "article", "words"])
df_multi_keyword = df_multi_keyword[0:5]
df_multi_keyword

id  \
1     梅雨季來臨，文旦黑點病易發生，請注意病徵，以及早加強防治措施。 5月已進入梅雨季節，近日連續...   
10    天氣多變溫差大，近山區及偏施氮肥田區稻熱病發病較為嚴重，籲請農友注意防治。花蓮區農改場、防檢...   
1000  新聞稿-稻熱病進入好發季節，防檢局籲請農友加強防範 行政院農業委員會動植物防疫檢疫局（以下簡...   
1005  稻熱病進入好發季節，防檢局籲請農友加強防治 農委會防檢局表示，自3月起全國各地水稻生長陸續進...   
1007  乍暖還寒，防檢局籲請農友加強防治稻熱病 農委會防檢局表示，全國各地水稻生長陸續進入分蘗期，因...   

                       article  \
1     ['chem', 'crop', 'pest']   
10    ['chem', 'crop', 'pest']   
1000          ['crop', 'pest']   
1005          ['crop', 'pest']   
1007          ['crop', 'pest']   

                                                  words  
1     ['鋅錳乃浦', '鋅錳乃浦', '鋅錳乃浦水懸劑', '鋅錳乃浦可濕性粉劑', '錳乃浦'...  
10    ['亞磷酸', '微生物製劑', '三賽唑', '三賽唑', '三賽唑可濕性粉劑', '三賽...  
1000  ['水稻', '水稻', '水稻', '水稻', '水稻', '水稻', '稻熱病', '稻...  
1005  ['水稻', '水稻', '水稻', '水稻', '水稻', '水稻', '稻熱病', '稻...  
1007  ['水稻', '水稻', '水稻', '水稻', '稻熱病', '稻熱病', '稻熱病', ...

In [13]:
# compute tf unigram
vectorizer = CountVectorizer() 
unigram_cv = vectorizer.fit_transform(df_unigram.words)
unigram_tf_vector = unigram_cv.toarray()
unigram_tf_vector

array([[0, 0, 0, ..., 0, 0, 2],
       [4, 2, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], dtype=int64)

In [14]:
# compute tf once_keyword
vectorizer = CountVectorizer() 
once_keyword_cv = vectorizer.fit_transform(df_once_keyword.words)
once_keyword_tf_vector = once_keyword_cv.toarray()
once_keyword_tf_vector

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
        0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0]], dtype=int64)

In [18]:
# compute tf multi_keyword
vectorizer = CountVectorizer() 
multi_keyword_cv = vectorizer.fit_transform(df_multi_keyword.words)
multi_keyword_tf_vector = multi_keyword_cv.toarray()
multi_keyword_tf_vector

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,
         0,  0,  0,  0,  2,  1,  1,  2,  1,  2],
       [ 2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  3,  6,  0,
         1,  1,  1,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  6, 14,  2,
         3,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  6, 14,  2,
         3,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4, 10,  0,
         2,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int64)

In [ ]:
# End of file